name: CodeQL

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
  schedule:
    # run every day at 1AM
    - cron: "0 1 * * *"

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'javascript'

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
